/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estudio1;

import Modelo.Usuario;
import Screens.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author alexa
 */
public class Parte4 extends javax.swing.JFrame {

    Color azul;
    Usuario us;
    public Parte4(Usuario usuario) {
        initComponents();
        us = usuario;
        azul = new Color(137,179,199);
        initStyles();
    }

    private Parte4() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public JPanel getFondo(){
        return fondo;
    }
    
    private void initStyles(){

    }
    
    private void changeFondo(JPanel fondos){   
        fondo.setSize(1351,810);
        fondos.setLocation(0,0);
        
        fondo.removeAll();
        fondo.setLayout(new java.awt.BorderLayout());
        fondo.add(fondos, BorderLayout.CENTER);
        fondo.revalidate();
        fondo.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new Vista.PanelRound();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        panelRound14 = new Vista.PanelRound();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d31 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        d10 = new javax.swing.JLabel();
        panelRound16 = new Vista.PanelRound();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 202, 216));

        jPanel1.setBackground(new java.awt.Color(172, 202, 216));

        fondo.setBackground(new java.awt.Color(237, 237, 237));
        fondo.setPreferredSize(new java.awt.Dimension(1351, 810));
        fondo.setRoundBottomLeft(100);
        fondo.setRoundBottomRight(100);
        fondo.setRoundTopLeft(100);
        fondo.setRoundTopRight(100);
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 720, 140, 50));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("Ondas");
        fondo.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 60, 40));

        panelRound14.setBackground(new java.awt.Color(137, 179, 199));
        panelRound14.setRoundBottomLeft(100);
        panelRound14.setRoundBottomRight(100);
        panelRound14.setRoundTopLeft(100);
        panelRound14.setRoundTopRight(100);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        panelRound14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        panelRound14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ondas según el medio en que se propagan");
        panelRound14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 40));

        fondo.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 60));

        d1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d1.setText("Una onda gravitatoria es una onda invisible, aunque increíblemente rápida,");
        fondo.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 810, 30));

        d2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d2.setText(" que se produce en el espacio. Las ondas gravitatorias se desplazan a la ");
        fondo.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 820, 30));

        d3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d3.setText("velocidad de la luz (186 000 millas o 300 000 kilómetros por segundo). ");
        fondo.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 780, 30));

        d31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d31.setText("Estas ondas contraen y estiran cualquier cosa que encuentran en su camino.");
        fondo.add(d31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 830, 30));

        d5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d5.setText("3. Dos agujeros negros que orbitan entre sí y se fusionan.");
        fondo.add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 640, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Atras");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 720, 140, 50));

        d10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d10.setText("2. Dos estrellas grandes que orbitan entre sí. ");
        fondo.add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 540, 30));

        panelRound16.setBackground(new java.awt.Color(172, 202, 216));
        panelRound16.setRoundBottomLeft(100);
        panelRound16.setRoundBottomRight(100);
        panelRound16.setRoundTopLeft(100);
        panelRound16.setRoundTopRight(100);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("5. Ondas gravitatorias");
        panelRound16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 50));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        panelRound16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        panelRound16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        fondo.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 380, 70));

        d11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d11.setText("Ejemplos de acciones que desatan una onda gravitatoria");
        fondo.add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 700, 30));

        d12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d12.setText("1. La explosión asimétrica de una estrella, llamada supernova.");
        fondo.add(d12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 680, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/onda5.jpg"))); // NOI18N
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 390, 460));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Parte5 p2 = new Parte5(us);
       changeFondo(p2.getFondo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Parte3 p1 = new Parte3(us);
        changeFondo(p1.getFondo());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parte4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parte4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d31;
    private javax.swing.JLabel d5;
    private Vista.PanelRound fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private Vista.PanelRound panelRound14;
    private Vista.PanelRound panelRound16;
    // End of variables declaration//GEN-END:variables
}
