/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estudio1;

import Modelo.Usuario;
import Screens.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author alexa
 */
public class Parte3 extends javax.swing.JFrame {

    Color azul;
    Usuario us;
    public Parte3(Usuario usuario) {
        initComponents();
        us = usuario;
        azul = new Color(137,179,199);
        initStyles();
    }

    private Parte3() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public JPanel getFondo(){
        return fondo;
    }
    
    private void initStyles(){

    }
    
    private void changeFondo(JPanel fondos){   
        fondo.setSize(1351,810);
        fondos.setLocation(0,0);
        
        fondo.removeAll();
        fondo.setLayout(new java.awt.BorderLayout());
        fondo.add(fondos, BorderLayout.CENTER);
        fondo.revalidate();
        fondo.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new Vista.PanelRound();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        d51 = new javax.swing.JLabel();
        panelRound14 = new Vista.PanelRound();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d31 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d61 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelRound15 = new Vista.PanelRound();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        panelRound16 = new Vista.PanelRound();
        jLabel26 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        d13 = new javax.swing.JLabel();
        d14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 202, 216));

        jPanel1.setBackground(new java.awt.Color(172, 202, 216));

        fondo.setBackground(new java.awt.Color(237, 237, 237));
        fondo.setPreferredSize(new java.awt.Dimension(1351, 810));
        fondo.setRoundBottomLeft(100);
        fondo.setRoundBottomRight(100);
        fondo.setRoundTopLeft(100);
        fondo.setRoundTopRight(100);
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 720, 140, 50));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("Ondas");
        fondo.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 60, 40));

        d51.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d51.setText("Las ondas electromagnéticas nacen cuando un campo eléctrico entra en contacto ");
        fondo.add(d51, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 950, -1));

        panelRound14.setBackground(new java.awt.Color(137, 179, 199));
        panelRound14.setRoundBottomLeft(100);
        panelRound14.setRoundBottomRight(100);
        panelRound14.setRoundTopLeft(100);
        panelRound14.setRoundTopRight(100);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        panelRound14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        panelRound14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ondas según el medio en que se propagan");
        panelRound14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 40));

        fondo.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 60));

        d1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d1.setText("Para que exista una onda mecánica es necesario que haya una fuente ");
        fondo.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 770, 40));

        d2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d2.setText("que genere la perturbación y un medio por el cual dicha perturbación ");
        fondo.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 780, 40));

        d4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d4.setText("presión, para propagarse efectivamente");
        fondo.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 440, 40));

        d3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d3.setText("pueda propagarse. Además, se necesita un medio elástico (líquido, ");
        fondo.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 740, 40));

        d31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d31.setText("gaseoso o sólido) y de condiciones determinadas de temperatura y ");
        fondo.add(d31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 730, 40));

        d7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/onda3.png"))); // NOI18N
        fondo.add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 460, 190));

        d5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d5.setText("3. Transmisión del sonido");
        fondo.add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, 290, 30));

        d6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d6.setText("con un campo magnético. De ahí que se conozcan como ondas electromagnéticas. ");
        fondo.add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 940, 30));

        d61.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d61.setText("No necesita un medio para propagarse o viajar de un lugar a otro.");
        fondo.add(d61, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 720, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Atras");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 720, 140, 50));

        panelRound15.setBackground(new java.awt.Color(172, 202, 216));
        panelRound15.setRoundBottomLeft(100);
        panelRound15.setRoundBottomRight(100);
        panelRound15.setRoundTopLeft(100);
        panelRound15.setRoundTopRight(100);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        panelRound15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        panelRound15.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("4. Ondas Electromagnéticas");
        panelRound15.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, 50));

        fondo.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 470, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/onda4.png"))); // NOI18N
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        d8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d8.setText("3. Microondas");
        fondo.add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 680, 210, 30));

        d9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d9.setText("Ejemplos de ondas electromagnéticas");
        fondo.add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 460, 30));

        d10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d10.setText("2. La vibración de una cuerda de guitarra  ");
        fondo.add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 460, 30));

        panelRound16.setBackground(new java.awt.Color(172, 202, 216));
        panelRound16.setRoundBottomLeft(100);
        panelRound16.setRoundBottomRight(100);
        panelRound16.setRoundTopLeft(100);
        panelRound16.setRoundTopRight(100);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("3. Ondas Mecánicas");
        panelRound16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 50));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        panelRound16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        panelRound16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        fondo.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 380, 70));

        d11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d11.setText("Ejemplos de ondas mecánicas");
        fondo.add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 460, 30));

        d12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d12.setText("1. El movimiento de un resorte ");
        fondo.add(d12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 360, 30));

        d13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d13.setText("1. Ondas de radio");
        fondo.add(d13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 210, 30));

        d14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d14.setText("2. Radar");
        fondo.add(d14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 680, 210, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Parte4 p2 = new Parte4(us);
       changeFondo(p2.getFondo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Parte2 p1 = new Parte2(us);
        changeFondo(p1.getFondo());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parte3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parte3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d31;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d51;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d61;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private Vista.PanelRound fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private Vista.PanelRound panelRound14;
    private Vista.PanelRound panelRound15;
    private Vista.PanelRound panelRound16;
    // End of variables declaration//GEN-END:variables
}
