/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estudio1;

import Modelo.Usuario;
import Screens.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author alexa
 */
public class Parte7 extends javax.swing.JFrame {

    Color azul;
    Usuario us;
    public Parte7(Usuario usuario) {
        initComponents();
        us = usuario;
        azul = new Color(137,179,199);
        initStyles();
    }

    private Parte7() {
        
    }

    
    public JPanel getFondo(){
        return fondo;
    }
    
    private void initStyles(){

    }
    
    private void changeFondo(JPanel fondos){   
        fondo.setSize(1351,810);
        fondos.setLocation(0,0);
        
        fondo.removeAll();
        fondo.setLayout(new java.awt.BorderLayout());
        fondo.add(fondos, BorderLayout.CENTER);
        fondo.revalidate();
        fondo.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new Vista.PanelRound();
        jButton1 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        panelRound14 = new Vista.PanelRound();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelRound16 = new Vista.PanelRound();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        panelRound18 = new Vista.PanelRound();
        jLabel28 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        d11 = new javax.swing.JLabel();
        d12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        panelRound15 = new Vista.PanelRound();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 202, 216));

        jPanel1.setBackground(new java.awt.Color(172, 202, 216));

        fondo.setBackground(new java.awt.Color(237, 237, 237));
        fondo.setPreferredSize(new java.awt.Dimension(1351, 810));
        fondo.setRoundBottomLeft(100);
        fondo.setRoundBottomRight(100);
        fondo.setRoundTopLeft(100);
        fondo.setRoundTopRight(100);
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 720, 140, 50));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("Ondas");
        fondo.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 60, 40));

        panelRound14.setBackground(new java.awt.Color(137, 179, 199));
        panelRound14.setRoundBottomLeft(100);
        panelRound14.setRoundBottomRight(100);
        panelRound14.setRoundTopLeft(100);
        panelRound14.setRoundTopRight(100);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        panelRound14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        panelRound14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ondas según el movimiento del medio");
        panelRound14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 40));

        fondo.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 390, 60));

        d1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d1.setText(" de la onda");
        fondo.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 140, 30));

        d2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d2.setText("todas direcciones.");
        fondo.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 230, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Atras");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 720, 140, 50));

        panelRound16.setBackground(new java.awt.Color(172, 202, 216));
        panelRound16.setRoundBottomLeft(100);
        panelRound16.setRoundBottomRight(100);
        panelRound16.setRoundTopLeft(100);
        panelRound16.setRoundTopRight(100);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        panelRound16.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        panelRound16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("11. Onda Longitudinal ");
        panelRound16.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 50));

        fondo.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 440, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/onda9.png"))); // NOI18N
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 280, 250));

        d5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        d5.setText("Ej: las ondas sonoras y las ondas electromagnéticas");
        fondo.add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 680, 30));

        d7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d7.setText("se conocen también como ondas esféricas, porque sus frentes de ondas son esferas ");
        fondo.add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 940, 30));

        d9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d9.setText("concéntricas que salen de la fuente de perturbación expandiéndose en ");
        fondo.add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 780, 30));

        panelRound18.setBackground(new java.awt.Color(172, 202, 216));
        panelRound18.setRoundBottomLeft(100);
        panelRound18.setRoundBottomRight(100);
        panelRound18.setRoundTopLeft(100);
        panelRound18.setRoundTopRight(100);
        panelRound18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("10. Ondas tridimensionales");
        panelRound18.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 50));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        panelRound18.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        panelRound18.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        fondo.add(panelRound18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 440, 70));

        d10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d10.setText("Son ondas que se propagan en tres dimensiones. Las ondas tridimensionales ");
        fondo.add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 870, 30));

        d11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d11.setText("Las ondas longitudinales son aquellas ondas en las que ");
        fondo.add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 640, 30));

        d12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d12.setText("la oscilación de la propiedad física que genera la onda ");
        fondo.add(d12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 600, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/944c50a8585f702954d3aa287b3dd4392da1b554.jpg"))); // NOI18N
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        d3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        d3.setText("ocurre en la misma dirección que el desplazamiento ");
        fondo.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, 620, 30));

        panelRound15.setBackground(new java.awt.Color(137, 179, 199));
        panelRound15.setRoundBottomLeft(100);
        panelRound15.setRoundBottomRight(100);
        panelRound15.setRoundTopLeft(100);
        panelRound15.setRoundTopRight(100);
        panelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        panelRound15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 630, 40));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        panelRound15.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 320, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Ondas según su dirección");
        panelRound15.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 40));

        fondo.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 350, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Parte8 p2 = new Parte8(us);
       changeFondo(p2.getFondo());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Parte6 p1 = new Parte6(us);
        changeFondo(p1.getFondo());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parte7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parte7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parte7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parte7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
      
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parte7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d9;
    private Vista.PanelRound fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private Vista.PanelRound panelRound14;
    private Vista.PanelRound panelRound15;
    private Vista.PanelRound panelRound16;
    private Vista.PanelRound panelRound18;
    // End of variables declaration//GEN-END:variables
}
