/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuario;
import Screens.Estudio;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author alexa
 */
public class Home extends javax.swing.JFrame {

    Usuario usuario;
    public Home(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private Home() {

    }
    
    public void showFondo(JPanel fondo){   
        fondo.setSize(1351,810);
        fondo.setLocation(0,0);
        
        content.removeAll();
        content.setLayout(new java.awt.BorderLayout());
        content.add(fondo, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Vista.PanelRound();
        boton4 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        content = new Vista.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(172, 202, 216));

        panelRound1.setBackground(new java.awt.Color(231, 231, 231));
        panelRound1.setRoundBottomLeft(100);
        panelRound1.setRoundBottomRight(100);
        panelRound1.setRoundTopLeft(100);
        panelRound1.setRoundTopRight(100);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton4.setBackground(new java.awt.Color(231, 231, 231));
        boton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/progreso 2.png"))); // NOI18N
        boton4.setText("Mi Progreso");
        boton4.setBorder(null);
        boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton4.setMargin(new java.awt.Insets(4, 14, 2, 14));
        panelRound1.add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 454, 130));

        boton1.setBackground(new java.awt.Color(231, 231, 231));
        boton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa-icono-silueta 2.png"))); // NOI18N
        boton1.setText("Inicio");
        boton1.setBorder(null);
        boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton1.setMargin(new java.awt.Insets(4, 14, 2, 14));
        panelRound1.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 454, 130));

        boton2.setBackground(new java.awt.Color(231, 231, 231));
        boton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/marcador 2.png"))); // NOI18N
        boton2.setText("Estudiar");
        boton2.setBorder(null);
        boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton2.setMargin(new java.awt.Insets(4, 14, 2, 14));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        panelRound1.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 454, 130));

        boton3.setBackground(new java.awt.Color(231, 231, 231));
        boton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pulgares-hacia-arriba 2.png"))); // NOI18N
        boton3.setText("Practicar");
        boton3.setBorder(null);
        boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton3.setMargin(new java.awt.Insets(4, 14, 2, 14));
        panelRound1.add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 454, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/matematicas 2 (2).png"))); // NOI18N
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        content.setBackground(new java.awt.Color(237, 237, 237));
        content.setPreferredSize(new java.awt.Dimension(1351, 810));
        content.setRoundBottomLeft(100);
        content.setRoundBottomRight(100);
        content.setRoundTopLeft(100);
        content.setRoundTopRight(100);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1351, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 1, 1870, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        Estudio es = new Estudio(usuario);
        showFondo(es.getFondo());
    }//GEN-LAST:event_boton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private Vista.PanelRound content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private Vista.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
