/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Controlador.SeccionDAO;
import Estudio1.Parte1;
import Modelo.Usuario;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author alexa
 */
public class Estudio extends javax.swing.JFrame {

    Usuario usuario;
    public Estudio(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        barraProgresiva();
    }

    private Estudio() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public JPanel getFondo(){
        return fondo;
    }
    
    private void changeFondo(JPanel fondos){   
        fondo.setSize(1351,810);
        fondos.setLocation(0,0);
        
        fondo.removeAll();
        fondo.setLayout(new java.awt.BorderLayout());
        fondo.add(fondos, BorderLayout.CENTER);
        fondo.revalidate();
        fondo.repaint();
       
    }
    
    private void barraProgresiva(){
        SeccionDAO sd = new SeccionDAO();
        int cien = 8;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new Vista.PanelRound();
        panelRound6 = new Vista.PanelRound();
        panelRound7 = new Vista.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar6 = new javax.swing.JProgressBar();
        panelRound13 = new Vista.PanelRound();
        panelRound14 = new Vista.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        panelRound15 = new Vista.PanelRound();
        panelRound16 = new Vista.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        panelRound17 = new Vista.PanelRound();
        panelRound18 = new Vista.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jProgressBar3 = new javax.swing.JProgressBar();
        panelRound19 = new Vista.PanelRound();
        panelRound20 = new Vista.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jProgressBar4 = new javax.swing.JProgressBar();
        panelRound21 = new Vista.PanelRound();
        panelRound22 = new Vista.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jProgressBar5 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 202, 216));

        jPanel1.setBackground(new java.awt.Color(172, 202, 216));

        fondo.setBackground(new java.awt.Color(237, 237, 237));
        fondo.setRoundBottomLeft(100);
        fondo.setRoundBottomRight(100);
        fondo.setRoundTopLeft(100);
        fondo.setRoundTopRight(100);
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound6.setBackground(new java.awt.Color(172, 202, 216));
        panelRound6.setRoundBottomLeft(100);
        panelRound6.setRoundBottomRight(100);
        panelRound6.setRoundTopLeft(100);
        panelRound6.setRoundTopRight(100);

        panelRound7.setBackground(new java.awt.Color(237, 237, 237));
        panelRound7.setRoundBottomLeft(100);
        panelRound7.setRoundBottomRight(100);
        panelRound7.setRoundTopLeft(100);
        panelRound7.setRoundTopRight(100);
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 157, 183));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Plan de estudio 6");
        panelRound7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ondas-de-radio.png"))); // NOI18N
        panelRound7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 77, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tipos de ondas");
        panelRound7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRound7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));
        panelRound7.add(jProgressBar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 340, 290));

        panelRound13.setBackground(new java.awt.Color(172, 202, 216));
        panelRound13.setRoundBottomLeft(100);
        panelRound13.setRoundBottomRight(100);
        panelRound13.setRoundTopLeft(100);
        panelRound13.setRoundTopRight(100);

        panelRound14.setBackground(new java.awt.Color(237, 237, 237));
        panelRound14.setRoundBottomLeft(100);
        panelRound14.setRoundBottomRight(100);
        panelRound14.setRoundTopLeft(100);
        panelRound14.setRoundTopRight(100);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 157, 183));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Plan de estudio 1");
        panelRound14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ondas-de-radio.png"))); // NOI18N
        panelRound14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 77, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipos de ondas");
        panelRound14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Ingresar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound14.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));
        panelRound14.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound14, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 340, 290));

        panelRound15.setBackground(new java.awt.Color(172, 202, 216));
        panelRound15.setRoundBottomLeft(100);
        panelRound15.setRoundBottomRight(100);
        panelRound15.setRoundTopLeft(100);
        panelRound15.setRoundTopRight(100);

        panelRound16.setBackground(new java.awt.Color(237, 237, 237));
        panelRound16.setRoundBottomLeft(100);
        panelRound16.setRoundBottomRight(100);
        panelRound16.setRoundTopLeft(100);
        panelRound16.setRoundTopRight(100);
        panelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 157, 183));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Plan de estudio 2");
        panelRound16.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ondas-de-radio.png"))); // NOI18N
        panelRound16.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 77, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tipos de ondas");
        panelRound16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Ingresar");
        jButton3.setBorder(null);
        panelRound16.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));
        panelRound16.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound16, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 340, 290));

        panelRound17.setBackground(new java.awt.Color(172, 202, 216));
        panelRound17.setRoundBottomLeft(100);
        panelRound17.setRoundBottomRight(100);
        panelRound17.setRoundTopLeft(100);
        panelRound17.setRoundTopRight(100);

        panelRound18.setBackground(new java.awt.Color(237, 237, 237));
        panelRound18.setRoundBottomLeft(100);
        panelRound18.setRoundBottomRight(100);
        panelRound18.setRoundTopLeft(100);
        panelRound18.setRoundTopRight(100);
        panelRound18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 157, 183));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Plan de estudio 3");
        panelRound18.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ondas-de-radio.png"))); // NOI18N
        panelRound18.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 77, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tipos de ondas");
        panelRound18.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Ingresar");
        jButton4.setBorder(null);
        panelRound18.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));
        panelRound18.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        javax.swing.GroupLayout panelRound17Layout = new javax.swing.GroupLayout(panelRound17);
        panelRound17.setLayout(panelRound17Layout);
        panelRound17Layout.setHorizontalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound17Layout.setVerticalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound18, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(panelRound17, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 340, 290));

        panelRound19.setBackground(new java.awt.Color(172, 202, 216));
        panelRound19.setRoundBottomLeft(100);
        panelRound19.setRoundBottomRight(100);
        panelRound19.setRoundTopLeft(100);
        panelRound19.setRoundTopRight(100);

        panelRound20.setBackground(new java.awt.Color(237, 237, 237));
        panelRound20.setRoundBottomLeft(100);
        panelRound20.setRoundBottomRight(100);
        panelRound20.setRoundTopLeft(100);
        panelRound20.setRoundTopRight(100);
        panelRound20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 157, 183));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Plan de estudio 4");
        panelRound20.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ondas-de-radio.png"))); // NOI18N
        panelRound20.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 77, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tipos de ondas");
        panelRound20.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Ingresar");
        jButton5.setBorder(null);
        panelRound20.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));
        panelRound20.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        javax.swing.GroupLayout panelRound19Layout = new javax.swing.GroupLayout(panelRound19);
        panelRound19.setLayout(panelRound19Layout);
        panelRound19Layout.setHorizontalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound19Layout.setVerticalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound20, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(panelRound19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 340, 290));

        panelRound21.setBackground(new java.awt.Color(172, 202, 216));
        panelRound21.setRoundBottomLeft(100);
        panelRound21.setRoundBottomRight(100);
        panelRound21.setRoundTopLeft(100);
        panelRound21.setRoundTopRight(100);

        panelRound22.setBackground(new java.awt.Color(237, 237, 237));
        panelRound22.setRoundBottomLeft(100);
        panelRound22.setRoundBottomRight(100);
        panelRound22.setRoundTopLeft(100);
        panelRound22.setRoundTopRight(100);
        panelRound22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 157, 183));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Plan de estudio 5");
        panelRound22.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ondas-de-radio.png"))); // NOI18N
        panelRound22.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 77, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Tipos de ondas");
        panelRound22.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("Ingresar");
        jButton6.setBorder(null);
        panelRound22.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 40));
        panelRound22.add(jProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, -1));

        javax.swing.GroupLayout panelRound21Layout = new javax.swing.GroupLayout(panelRound21);
        panelRound21.setLayout(panelRound21Layout);
        panelRound21Layout.setHorizontalGroup(
            panelRound21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound21Layout.setVerticalGroup(
            panelRound21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound22, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        fondo.add(panelRound21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 340, 290));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Parte1 p1 = new Parte1(usuario);
        changeFondo(p1.getFondo());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudio().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.PanelRound fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private Vista.PanelRound panelRound13;
    private Vista.PanelRound panelRound14;
    private Vista.PanelRound panelRound15;
    private Vista.PanelRound panelRound16;
    private Vista.PanelRound panelRound17;
    private Vista.PanelRound panelRound18;
    private Vista.PanelRound panelRound19;
    private Vista.PanelRound panelRound20;
    private Vista.PanelRound panelRound21;
    private Vista.PanelRound panelRound22;
    private Vista.PanelRound panelRound6;
    private Vista.PanelRound panelRound7;
    // End of variables declaration//GEN-END:variables
}
